blank_issues_enabled: false
contact_links:
  - name: 💬 Discussions
    url: https://github.com/SimeonTsvetanov/Cap-Me-Too/discussions
    about: Ask questions and discuss ideas with the community
  - name: 📖 Documentation
    url: https://github.com/SimeonTsvetanov/Cap-Me-Too/wiki
    about: Check out our comprehensive documentation
